### ISSUE TITLE
Not working on AOSP android pie

### ISSUE THREAD

**Issue by junomarian** [stefansundin/android-disable-direct-share#3]
I followed the steps, I used miXplorer to put that file at /data/system/ifw/.  Permission of that file is now -rw-r--r--.

**Comment by eberhardweber** [comment]
Same situation on LineageOS 16.0 for me.

**Comment by junomarian** [comment]
Problem Solved, flashing zip via twrp worked for me, But didn't worked with simply putting file via File Manager.
